services:
  db:
    image: postgis/postgis:14-3.2
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5433
    networks:
      main:
        aliases:
          - db

  tiles:
    image: urbica/martin
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgres://mapper:mapp1nPswrd@db/postgres
    depends_on:
      - db
      - api
    networks:
      main:
        aliases:
          - tiles


  api:
    build:
      context: ./api
    volumes:
      - type: bind
        source: ./api
        target: /code
    ports:
      - "8000:8000"
    env_file: api/.env.development
    restart: always
    networks:
      main:
    depends_on:
      - db


networks:
  main:
